SUP-107 : count correctly nodes when doing a jcr query
Jahia/tools pull request #33
Opened 2021-12-23 13:17 UTC by jsinovassin

https://jira.jahia.org/browse/SUP-107

2021-12-23 16:41 UTC, bpapez requested changes

2021-12-23 16:41 UTC, bpapez commented on src/main/resources/jcrQuery.jsp
> +
I think there should be a better way and that it is not good to try loading all rows especially if there is a huge number of results - you should test the performance on a large installation and with a query, which will return nearly all nodes.

I think the better approach is to use nodes.getSize() - that variable is set on line 291 (prior your patch), but only under the condition that there is just one selector name in the query (e.g. SELECT * FROM would qualify for that). Perhaps you could even ignore the other cases and keep them counting the rows, but for the case of nodes, just add

            pageContext.setAttribute("count", JCRContentUtils.size(result.getNodes()));

on line 292

2021-12-27 09:42 UTC, jsinovassin commented on src/main/resources/jcrQuery.jsp
> +
I tried with the query `SELECT * FROM [nt:base]` on a local environment with the site digitall installed and I get the result in 500ms. 

I can't only use JCRContentUtils.size(result.getNodes()) because it's getting the size of nodes for every languages so the result which is displayed in the page is not correct. 

For example if there is 22 nodes in english and 1 node in French and I filter with the language Dutch, `JCRContentUtils.size(result.getNodes())` or `JCRContentUtils.size(result.getRows())` will return 23 instead of 0.

When I do a loop like I did in 273 I get the correct result because I get the count for the nodes which are only displayed in the selected language.

2021-12-30 15:43 UTC, bpapez commented on src/main/resources/jcrQuery.jsp
> +
I was now reading the original ticket https://support.jahia.com/browse/ARKEMA-390 - I wonder if it is enough to solve the problem at the query tool level, because the customer is talking about a query in his own code/script, which is not working. Then the discussion goes towards the query tool, because of trying to reproduce the original issue. So at the end just solving it at the query tool level may not be enough, as the problem will still be there in the code/scripts, where the customer executes the query.

Also testing the performance of the changes just with Digitall is not really representative, because customers - like Arkema, who reported the issue - have much larger sites, with many languages. Having to load all the results as JCR nodes in a site with many thousands of content nodes running into exceptions can be slow and resource intensive, so maybe you should test your changes on an Arkema copy on the cloud. If we keep your solution and if the performance could become very slow, then perhaps your code should be just activated optionally via a new checkbox (similar to "Show actions" and "Use Jackrabbit session" on the top-right).

Regarding some other filtering in queries there already is logic in org.apache.jackrabbit.core.query.lucene.JahiaLuceneQueryFactoryImpl.execute , which takes care about ACL, visibility rules or invalid languages. The j:invalidLanguages property on a node is set via content editor, when you open Advanced options -> Content - then at the top there is a "Valid display languages" section, where you can make a content invalid for a certain language. I guess due to the code in JahiaLuceneQueryFactoryImpl.execute this is handled there and will IMHO correctly handle result sizes, if a content is made invalid for a language. 

So maybe the current problem is also something, which could or should be solved at the JahiaLuceneQueryFactoryImpl.execute level, but you have to be very careful there to not create a regression or performance issue, as all queries in Jahia are going through this method.

Some more infos: 
* You can see in Tools -> JCR Query statistics , that the queries are automatically getting a jcr:language clause added (checking for jcr:language IS NULL or jcr:language = "<session-language>") - this is done in the QueryModifierAndOptimizerVisitor class if no jcr:language clause has been explicitly set in the query. So the results size you see are because of the jcr:languages IS NULL part, which returns the main node (not the translation nodes).
* In the Jahia Site Settings there is a Languages section, where you can add/remove languages per site and de-/activate them for Default or Live. You can also set an option, that if content is not yet translated for a language, then the content should still be displayed in the default language (English in Digitall). So if you add Dutch and activate that option at the bottom, suddenly the Dutch results will be displayed in the query results. This logic is in the JCRNodeWrapperImpl.checkValidity -> checkLanguageValidity.

2022-01-28 16:59 UTC, jsinovassin commented on src/main/resources/jcrQuery.jsp
> +
In my opinion, we should not modify JahiaLuceneQueryFactoryImpl.execute to get the correct number of node which are returned by the query.

We should let the query return the result as it's doing now, because when specifying the language in the query the correct number is returned for example: `SELECT * FROM [jnt:page] WHERE ISDESCENDANTNODE('/sites') AND [jcr:language] = 'en'` returns the expected pages only in french and the number of result is correct.

When we don't specify language in the query, it's the session language which is consider when displaying the result. 
The query returns all the results without the consideration of the language so the number of result will be the number on nodes returned by the query. But we are using our custom NodeIteratorWrapper which try to get the content is the language present in the session. So if the content is not present, the content will be skipped when the results will be displayed.

2022-02-01 09:54 UTC, dgriffon approved these changes

2022-02-02 05:52 UTC, merged