BACKLOG-22357: Introduce Import-Package checker tool
Jahia/tools pull request #61
Opened 2024-02-09 17:46 UTC by jkevan

2024-02-16 10:14 UTC, jayblanc approved these changes
Maybe another ticket for a JUnit Test using mocked FrameworkService will allow to test the OSGIPackageHEaderChecker ?

2024-02-20 12:07 UTC, sergehuber requested changes
Hello Kevan, thanks for the PR, nice work !

I just found some minor issues.

2024-02-20 12:07 UTC, sergehuber commented on src/main/java/org/jahia/modules/tools/gql/admin/ToolsGraphQL.java
> +            @GraphQLName("versionMissing") @GraphQLDescription("will return only import-package matching the given version") @GraphQLDefaultValue(GqlUtils.SupplierFalse.class) boolean versionMissing
I think this description is not correct ?

2024-02-20 12:07 UTC, sergehuber commented on src/main/java/org/jahia/modules/tools/gql/admin/osgi/BundleResultEntry.java
> +public abstract class BundleResultEntry {
Could you please add a short class description ?

2024-02-20 15:47 UTC, sergehuber approved these changes

2024-02-21 08:16 UTC, merged